- name: multi playbook
  hosts: localhost
  connection: local
  tasks:
    - name: print the msg
      ansible.builtin.debug:
        msg: "this is a multi playbook example"

    - name: ping the frontend servers
      hosts: localhost
      tasks:
      - name: ping the remote hosts
        ansible.builtin.ping:     